language: ruby

cache:
  - bundler
  - yarn
addons:
  # Use a different PostgreSQL version than the default:
  postgresql: 13
  apt:
    update: true
    packages:
      - postgresql-13
      - postgresql-13-postgis-3
services:
  - postgresql
env:
  global:
    # A different port must be used when not using the
    # default PostgreSQL:
    - PGPORT=5433
  jobs:
    - DB_DATABASE=comic_app_test DB_PORT=5433 DB_USERNAME=postgres
before_install:
  - >-
    sudo sed -i
    -e '/local.*peer/s/postgres/all/'
    -e 's/peer\|md5/trust/g'
    /etc/postgresql/13/main/pg_hba.conf
  - sudo service postgresql@13-main restart
  - nvm install --lts

before_script:
  - bundle install --jobs=3 --retry=3
  - sudo psql -p 5433 -U postgres -c 'create database comic_app_test;'
script:
  - bundle exec rake test